export enum NameCheckItemType {
  CONFLICTS_CONDITIONAL = 'conflictsConditional',
  DESCRIPTIVE_MISSING = 'descriptiveMissing',
  DESIGNATIONS_CHECK_USE = 'designationsCheckUse',
  DESIGNATIONS_CHECK_USE_CP = 'designationsCheckUseCP',
  DESIGNATIONS_CHECK_USE_CCC = 'designationsCheckUseCCC',
  DESIGNATIONS_CHECK_USE_PROP = 'designationsCheckUseProp',
  DESIGNATIONS_MISMATCHED = 'designationsMismatched',
  DESIGNATIONS_MISPLACED = 'designationsMisplaced',
  DESIGNATIONS_MISSING = 'designationsMissing',
  DESIGNATIONS_MISSING_CP = 'designationsMissingCP',
  DESIGNATIONS_MISSING_CCC = 'designationsMissingCCC',
  DISTINCTIVE_MISSING = 'distinctiveMissing',
  EXACT_MATCH = 'exactMatch',
  EXACT_MATCH_XPRO = 'exactMatchXpro',
  LOADING = 'loading',
  NO_ISSUES = 'noIssues',
  RESTRICTED = 'restricted',
  SIMILAR_MATCH = 'similarMatch',
  SIMILAR_MATCH_XPRO = 'similarMatchXpro',
  SPECIAL_CHARACTERS = 'specialCharacters'
}
