/** Enum for NR State Code. */
export enum NrState {
  APPROVED = 'APPROVED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED', // NOT A VALID STATE
  COND_RESERVED = 'COND-RESERVE', // INTERIM STATE
  CONDITIONAL = 'CONDITIONAL',
  DRAFT = 'DRAFT',
  EXPIRED = 'EXPIRED', // NOT YET IMPLEMENTED
  IN_PROGRESS = 'INPROGRESS',
  ON_HOLD = 'HOLD',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  REFUND_REQUESTED = 'REFUND_REQUESTED',
  REFUNDED = 'REFUNDED', // NOT YET IMPLEMENTED
  REJECTED = 'REJECTED',
  RESERVED = 'RESERVED', // INTERIM STATE
}
