export const TOGGLE_PAYMENT_MODAL = 'togglePaymentModal'
export const PAYMENT_MODAL_IS_VISIBLE = 'paymentModalIsVisible'
export const PAYMENT_IS_IN_PROGRESS = 'paymentIsInProgress'

export const GET_PAYMENT = 'getPayment'
export const GET_PAYMENT_ID = 'getPaymentId'
export const GET_PAYMENT_TOKEN = 'getPaymentToken'
export const GET_PAYMENT_DETAILS = 'getPaymentDetails'
export const GET_PAYMENT_FEES = 'getPaymentFees'
export const GET_PAYMENT_REQUEST = 'getPaymentRequest'
export const GET_PAYMENT_INVOICE = 'getPaymentInvoice'
export const GET_PAYMENT_RECEIPT = 'getPaymentReceipt'

export const TOGGLE_RECEIPT_MODAL = 'toggleReceiptModal'
export const RECEIPT_MODAL_IS_VISIBLE = 'receiptModalIsVisible'

export const SET_PAYMENT_FEES = 'setPaymentFees'
export const SET_PAYMENT_REQUEST = 'setPaymentRequest'
export const SET_PAYMENT_IS_PROCESSING = 'setPaymentIsProcessing'
export const SET_PAYMENT = 'setPayment'
export const SET_PAYMENT_INVOICE = 'setPaymentInvoice'
export const SET_PAYMENT_RECEIPT = 'setPaymentReceipt'
export const START_PAYMENT_TIMEOUT_TIMER = 'startPaymentTimeoutTimer'
export const CLEAR_PAYMENT_TIMEOUT_TIMER = 'clearPaymentTimeoutTimer'
