export const HAS_ERRORS = 'HAS_ERRORS'
export const GET_ERROR = 'GET_ERROR'
export const GET_ERRORS = 'GET_ERRORS'
export const SET_ERROR = 'SET_ERROR'
export const SET_ERRORS = 'SET_ERRORS'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
