/** Enum for NR Action. */
export enum NrAction {
  CANCEL = 'CANCEL',
  EDIT = 'EDIT',
  REAPPLY = 'REAPPLY',
  RECEIPTS = 'RECEIPT',
  REFUND = 'REFUND',
  RESULTS = 'RESULT', // NOT YET IMPLEMENTED
  UPGRADE = 'UPGRADE',
  INCORPORATE = 'INCORPORATE',
}
