/** Enum for NR State Code. */
export enum NrState {
  APPROVED = 'APPROVED',
  CANCELLED = 'CANCELLED',
  CANCELLED2 = 'CANCELLED2', // FUTURE (Cancelled, Refund Requested)
  CONDITIONAL = 'CONDITIONAL',
  CONSUMED = 'CONSUMED',
  DRAFT = 'DRAFT',
  EXPIRED = 'EXPIRED',
  IN_PROGRESS = 'INPROGRESS',
  ON_HOLD = 'HOLD',
  REFUNDED = 'REFUNDED', // FUTURE
  REJECTED = 'REJECTED',
}
