/** Enum for NR State Code. */
export enum NrState {
  APPROVED = 'APPROVED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
  COND_RESERVE = 'COND_RESERVE',
  CONDITIONAL = 'CONDITIONAL',
  DRAFT = 'DRAFT',
  EXPIRED = 'EXPIRED',
  HOLD = 'HOLD',
  INPROGRESS = 'INPROGRESS',
  REFUND_REQUESTED = 'REFUND_REQUESTED',
  REFUNDED = 'REFUNDED', // NOT YET IMPLEMENTED
  REJECTED = 'REJECTED',
  RESERVED = 'RESERVED',
}
