name: NAMEREQUEST UI CI

on:
  push:
    branches:
      - "test-eves-branch"
  pull_request:
    branches:
      - "main" 

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  namerequest-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/frontend-ci.yaml@main
    with:
      app_name: "namerequest"
      working_directory: "./"
      codecov_flag: ""
