name: Name Request UI CI

on:
  pull_request:
    types: [assigned, synchronize]

jobs:
  name-request-ui-ci:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: ./client

    strategy:
      matrix:
        node-version: [14.15.1]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          make setup
        env:
          CI: true
      - name: Run Lint
        run: |
          make lint
        env:
          CI: true
      - name: Run Unit Tests
        run: |
          make test
        env:
          CI: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: codecov-name-request
          fail_ci_if_error: true
      - name: Run build
        run: |
          make build-nc
        env:
          CI: true
